cast_document_type:
  # see https://github.com/ArneBinder/pie-datasets/blob/main/src/pie_datasets/core/dataset_dict.py
  _processor_: pie_datasets.DatasetDict.cast_document_type
  new_document_type: ???
