_target_: src.utils.execute_pipeline
input:
  _target_: pie_datasets.DatasetDict.load_dataset
  path: pie/brat
  name: merge_fragmented_spans
  base_dataset_kwargs:
    url: "path/to/n2c2_ade.zip" # use public path
    file_name_blacklist:
      - "106967"
      - '110445'
      #- '115157'
    split_paths:
      train: 'n2c2_ade/train'
      test: 'n2c2_ade/test'
  document_converters:
    pytorch_ie.documents.TextDocumentWithLabeledSpansAndBinaryRelations:
      spans: labeled_spans
      relations: binary_relations
